// Generated by tools/hipaa-docs/build.js from content/training.js. Do not edit.
export const TRAINING_VERSION = "1.2";
export const TRAINING_PASSING_SCORE = 10;
export const TRAINING_MODULES: readonly { id: number; title: string }[] = [{"id":1,"title":"Module 1. Why this matters"},{"id":2,"title":"Module 2. What counts as protected health information"},{"id":3,"title":"Module 3. What the Helixona Assistant is, and is not"},{"id":4,"title":"Module 4. Signing in"},{"id":5,"title":"Module 5. Using it safely"},{"id":6,"title":"Module 6. Recognizing and reporting incidents"},{"id":7,"title":"Module 7. Consequences"}];
export const TRAINING_QUIZ: readonly { module: number; text: string; options: readonly string[]; answer: string; why: string }[] = [
  {
    "module": 1,
    "text": "Who does HIPAA apply to at Helixona?",
    "options": [
      "Only the doctors.",
      "The clinic and every member of its workforce, including administrative staff.",
      "Only the company that runs the software."
    ],
    "answer": "B",
    "why": "HIPAA duties apply to the clinic and to each workforce member."
  },
  {
    "module": 2,
    "text": "Which of these is PHI?",
    "options": [
      "A patient's name next to an appointment date.",
      "The clinic's address.",
      "A blank claim form."
    ],
    "answer": "A",
    "why": "A name with a date of care identifies the patient and relates to care."
  },
  {
    "module": 3,
    "text": "Which tool may receive patient information?",
    "options": [
      "Any AI chatbot with a good privacy policy.",
      "Only the Helixona Assistant at ai.helixona.com.",
      "Your personal account on a consumer AI product, if you delete the chat afterwards."
    ],
    "answer": "B",
    "why": "Only the approved tool has HIPAA agreements and the clinic's safeguards."
  },
  {
    "module": 3,
    "text": "Who is responsible for a clinical or billing decision made using the assistant's output?",
    "options": [
      "The assistant.",
      "Anthropic.",
      "The licensed staff member who reviews and uses it."
    ],
    "answer": "C",
    "why": "Licensed staff own every clinical and billing decision."
  },
  {
    "module": 4,
    "text": "A coworker is out sick and asks you to sign in with your account so they can finish a letter. What do you do?",
    "options": [
      "Share the code once.",
      "Decline; accounts are personal and an administrator can create one for them.",
      "Sign in for them on your computer."
    ],
    "answer": "B",
    "why": "Accounts are personal; every action must be attributable to one person."
  },
  {
    "module": 4,
    "text": "Your phone with the authenticator app is stolen on Saturday. When do you report it?",
    "options": [
      "Monday morning.",
      "The same day, to the Security Officer.",
      "Only if you notice unusual activity."
    ],
    "answer": "B",
    "why": "Same-day reporting lets an administrator disable the account or reset the authenticator."
  },
  {
    "module": 4,
    "text": "You are on a shared front-desk computer and step away for lunch. What do you do first?",
    "options": [
      "Nothing; the screen locks eventually.",
      "Sign out of the assistant.",
      "Close the browser tab only."
    ],
    "answer": "B",
    "why": "Signing out prevents someone else from using your session."
  },
  {
    "module": 5,
    "text": "You need the assistant to summarize one patient's EOB. The PDF you have covers ten patients. What is the right step?",
    "options": [
      "Upload the whole file.",
      "Upload only the pages for that patient, or redact the others.",
      "Paste all ten into the message."
    ],
    "answer": "B",
    "why": "Minimum necessary: include only the information the task needs."
  },
  {
    "module": 5,
    "text": "The assistant drafts an appeal letter with a claim number and denial code. Before sending it you must:",
    "options": [
      "Send it; the assistant is accurate.",
      "Check the claim number, dates and reasons against the source document.",
      "Ask the assistant if it is sure."
    ],
    "answer": "B",
    "why": "The assistant can be wrong; the person is responsible for the result."
  },
  {
    "module": 5,
    "text": "How long are conversations kept?",
    "options": [
      "Forever.",
      "30 days after the last activity, or until you delete them.",
      "Until the end of the year."
    ],
    "answer": "B",
    "why": "Retention is 30 days after the last activity; users may delete sooner."
  },
  {
    "module": 6,
    "text": "You notice a conversation in a shared project that contains a patient's full record for no work reason. What do you do?",
    "options": [
      "Ignore it.",
      "Report it to the Security Officer within an hour.",
      "Delete it yourself and say nothing."
    ],
    "answer": "B",
    "why": "Suspected incidents are reported within an hour and never handled alone."
  },
  {
    "module": 7,
    "text": "What can happen if you look at a patient's information without a work reason?",
    "options": [
      "Nothing, as long as you do not share it.",
      "Sanctions from retraining up to termination, and possibly legal penalties.",
      "A reminder email."
    ],
    "answer": "B",
    "why": "Access without a work reason is a violation; sanctions range up to termination and legal penalties may apply."
  }
];
