const { h1, h2, h3, p, b, i, note, bullets, numbered, table, kv, spacer, pageBreak, titleBlock, build } = require("../lib");
const policy = (id, title, purpose, statements, procedures) => [
  h1(`${id}. ${title}`),
  p([b("Purpose. "), purpose]),
  h3("Policy"),
  ...numbered(statements),
  ...(procedures ? [h3("Procedure"), ...numbered(procedures)] : []),
];
const children = [
  ...titleBlock("HIPAA Policies and Procedures", "Helixona Assistant (ai.helixona.com)", [
    ["Document", "Policies and procedures for the use and administration of the Helixona Assistant"],
    ["Applies to", "All Helixona workforce members with an account, and the administrators of the system"],
    ["Owner", "[Name], Privacy Officer, with [Name], Security Officer"],
    ["Version and date", "1.0, September 16, 2026"],
    ["Approved by", "[Name], Owner / Medical Director"],
    ["Review cycle", "Yearly, and after any significant change"],
  ]),
  pageBreak(),
  h1("Contents"),
  ...bullets([
    "P1. Scope, roles and responsibilities", "P2. Acceptable use of the assistant", "P3. Access control and account lifecycle", "P4. Authentication and device security",
    "P5. Data handling and retention", "P6. Security incidents and breach notification", "P7. Audit and monitoring", "P8. Contingency and backups",
    "P9. Vendors and agreements", "P10. Sanctions", "P11. Training", "P12. Policy management",
    "Appendix A. Onboarding and offboarding checklist", "Appendix B. Quarterly access review", "Appendix C. Security incident report form", "Appendix D. Definitions",
  ]),
  ...policy("P1", "Scope, roles and responsibilities",
    "Define who is responsible for protecting patient information in the Helixona Assistant.",
    [
      "These policies apply to every workforce member who has an account on the Helixona Assistant and to everyone who administers the system or the accounts it runs in (AWS, Anthropic Claude Console, the domain registrar).",
      [b("Privacy Officer "), "([Name]): owns these policies, approves accounts and roles, runs the quarterly access review, handles patient rights requests and breach notifications."],
      [b("Security Officer "), "([Name]): owns the risk analysis, the technical safeguards, monitoring, incident response and vendor agreements. May be the same person as the Privacy Officer in a small clinic."],
      [b("Administrators: "), "create, disable and re-enable accounts, assign roles, reset authenticators, and review the audit log as directed. Administrator accounts are limited to the minimum number needed, normally two."],
      [b("Workforce members: "), "follow these policies, complete training before first use, and report incidents immediately."],
      "The AWS account, the Anthropic organization and the domain are owned by the clinic. Access to them is limited to the Security Officer and one named backup.",
    ]),
  ...policy("P2", "Acceptable use of the assistant",
    "Ensure the assistant is used only for clinic work and that its output is used responsibly.",
    [
      "The assistant may be used for clinic operations: drafting letters and messages, summarizing and translating documents, analyzing explanation-of-benefits statements, claims and other administrative documents, and similar tasks.",
      "Use only the minimum necessary patient information for the task. Do not include information that is not needed to complete it.",
      "The assistant is a drafting and analysis aid. Licensed staff remain responsible for every clinical, billing and patient-facing decision. Every response is reviewed for accuracy before it is used or sent.",
      "The assistant is not used for clinical diagnosis or treatment decisions on its own, and its output is never sent to a patient without a person reading it first.",
      "Patient information is never entered into any other AI tool, chatbot or website, including personal accounts on consumer AI products. The Helixona Assistant is the only approved AI tool for PHI.",
      "Accounts are personal. Sharing an account, a password or an authenticator is prohibited.",
      "Use of the assistant for personal matters, or for any purpose outside the clinic's operations, is prohibited.",
      "A shared project is seen by the people its owner adds to it, and everyone in it sees and can continue the same conversations: add only the colleagues who need that work, and remove them when they no longer do. Projects shared with the clinic may be seen by every staff member. Do not place patient information in a project's name, description or instructions unless everyone who can see the project needs it.",
    ]),
  ...policy("P3", "Access control and account lifecycle",
    "Ensure that only authorized people have access, with the least privilege needed, and that access ends when it is no longer needed.",
    [
      "Accounts are created only by an administrator after approval by the Privacy Officer, for workforce members whose duties require the assistant.",
      "Each user receives the staff role unless the Privacy Officer approves the administrator role in writing. Administrators are limited to the minimum number needed.",
      "Access is removed the same business day a workforce member leaves, changes to a role that no longer needs it, or is placed on leave that removes their need for access.",
      "The Privacy Officer reviews the full user list and roles every quarter and records the review (Appendix B).",
      "A user whose authenticator is lost or replaced is verified in person or by a call-back to a known number before the authenticator is reset.",
    ],
    [
      "Onboarding: the manager requests access; the Privacy Officer approves; an administrator creates the account from the Administration page; the user receives a temporary password by email and, at first sign-in, sets a password, enrolls an authenticator app and completes the training inside the assistant before their first conversation.",
      "Role change: an administrator changes the role from the Administration page. The user is signed out and must sign in again.",
      "Offboarding: an administrator clicks Disable on the Administration page. All of the user's sessions are revoked immediately. The account is deleted after 30 days if it is not needed for the audit trail.",
      "Lost authenticator: after identity verification, an administrator clicks Reset MFA. The user is signed out and enrolls a new authenticator at the next sign-in.",
      "Record each step on the checklist in Appendix A.",
    ]),
  ...policy("P4", "Authentication and device security",
    "Protect accounts and the devices used to reach the assistant.",
    [
      "Every account uses a password of at least 12 characters with upper and lower case letters, a number and a symbol, and an authenticator app as a second factor. Both are enforced by the system.",
      "Passwords and authenticator codes are never shared, written down where others can see them, or entered anywhere other than ai.helixona.com.",
      "The assistant is used only on clinic-managed devices or personal devices approved by the Security Officer that have a screen lock, current updates and disk encryption.",
      "The assistant is not used on public or shared computers. On a shared clinic workstation, users sign out when they step away. Sessions end automatically after 15 minutes of inactivity.",
      "A lost or stolen phone, laptop or authenticator is reported to the Security Officer the same day so the account can be disabled or the authenticator reset.",
      "Members of the Anthropic Claude Console organization and users of the AWS account use two-factor authentication.",
    ]),
  ...policy("P5", "Data handling and retention",
    "Keep patient information only as long as needed and only where it is protected.",
    [
      "Conversations and uploaded files are deleted automatically 30 days after their last activity. Users delete conversations sooner when the work is finished.",
      "Uploaded files are limited to what the task requires. Do not upload documents about patients who are not the subject of the task.",
      "Assistant output that contains patient information is stored only in the clinic's approved systems (for example the health record or practice management system). It is not saved to personal devices, personal email or personal cloud storage.",
      "Screenshots of conversations containing patient information are not taken except when required to report an incident, and are then sent only to the Security Officer through the clinic's email.",
      "Patient information is not included in support requests, bug reports or messages to vendors. Describe the problem without the data.",
      "Project knowledge files are reviewed when the project is no longer active and the project is deleted, which removes its files.",
    ]),
  ...policy("P6", "Security incidents and breach notification",
    "Detect, contain and report security incidents, and notify affected individuals and authorities when the law requires it.",
    [
      "A security incident is any event that may have exposed, altered or made unavailable patient information, including a lost device, a phishing message that was acted on, a message sent to the wrong person, a suspected account compromise, or unusual activity in the audit log.",
      "Every workforce member reports a suspected incident to the Security Officer within one hour of noticing it. Reporting a suspected incident is never penalized.",
      "The Security Officer contains the incident first (disable the account, reset the authenticator, revoke sessions, rotate the API key if it may be exposed), then investigates using the audit log and CloudTrail, and records everything on the incident report form (Appendix C).",
      "The Privacy Officer performs the breach risk assessment required by 45 CFR 164.402 and documents the conclusion. Unless the assessment shows a low probability that the information was compromised, the event is treated as a breach.",
      "For a breach: affected individuals are notified without unreasonable delay and no later than 60 days after discovery; the Secretary of HHS is notified through the HHS breach portal (within 60 days for 500 or more individuals, otherwise within 60 days after the end of the calendar year); prominent media are notified for breaches affecting more than 500 residents of a state. California notification requirements (Civil Code 1798.82 and the Confidentiality of Medical Information Act) are also followed.",
      "Incident records are kept for six years.",
    ],
    [
      "Report: call or message the Security Officer; do not investigate on your own; do not delete anything.",
      "Contain: Security Officer disables the affected user on the Administration page and, if needed, resets the authenticator, rotates the Anthropic API key in AWS Secrets Manager and forces a new deployment.",
      "Assess: review Administration, Audit for the day(s) in question and the CloudTrail data events for the PHI tables and file bucket; identify what was accessed and by whom.",
      "Document: complete Appendix C within two business days.",
      "Decide and notify: Privacy Officer completes the breach risk assessment and, if required, the notifications above.",
      "Learn: update this policy, the risk analysis or the training if the incident shows a gap.",
    ]),
  ...policy("P7", "Audit and monitoring",
    "Make sure access to patient information is reviewed regularly.",
    [
      "The application records every sign-in, message turn, file upload, conversation deletion and administrative action with the user, time and outcome, and never the content.",
      "An administrator reviews Administration, Audit weekly for unexpected sign-ins, activity outside working hours, repeated failed sign-ins and administrative changes, and reports anything unusual to the Security Officer.",
      "The Security Officer reviews CloudWatch alarms and the CloudTrail data events for the PHI tables and file bucket monthly.",
      "Application logs are retained for one year; audit records and CloudTrail files are retained for six years.",
      "Reviews are recorded with the date, reviewer and findings.",
    ]),
  ...policy("P8", "Contingency and backups",
    "Keep patient information recoverable and keep the clinic operating during an outage.",
    [
      "All tables have point-in-time recovery, the file storage is versioned, and AWS Backup takes a daily backup retained for 35 days. Backups are encrypted with the clinic's key.",
      "The Security Officer performs and documents a restore test within 30 days of go-live and yearly afterwards.",
      "During an outage, staff continue with the clinic's manual processes. The assistant holds no record that the clinic cannot recreate from its primary systems.",
      "The infrastructure is defined as code in the clinic's repository and can be redeployed to the clinic's account from that definition.",
      "The Security Officer keeps a current contact list for the account owner, the domain registrar and the vendors.",
    ]),
  ...policy("P9", "Vendors and agreements",
    "Ensure every vendor that handles patient information is bound by a Business Associate Agreement.",
    [
      "Amazon Web Services handles patient information under the AWS Business Associate Addendum accepted in AWS Artifact for account 148274106093. Only services on the AWS HIPAA Eligible Services list are used for patient information.",
      "Anthropic handles patient information under its Business Associate Agreement, with HIPAA readiness enabled for the clinic's organization on September 15, 2026. Only features on Anthropic's HIPAA-eligible list are used, and the platform enforces this automatically.",
      "No other vendor, tool or AI service receives patient information from the assistant unless a Business Associate Agreement is in place and the Security Officer has approved it.",
      "Agreements are reviewed yearly and whenever a vendor changes its terms. Copies are kept with the compliance records.",
      "Outside contractors who would gain access to patient information sign a Business Associate Agreement before access is granted. Clinic workforce members do not need one.",
    ]),
  ...policy("P10", "Sanctions",
    "Apply consequences consistently when these policies are violated.",
    [
      "Violations of these policies result in sanctions proportionate to the violation, from documented retraining to termination, and referral to authorities when the law requires it.",
      "Examples of serious violations: sharing an account, entering patient information into an unapproved AI tool, looking up a patient without a work reason, or failing to report a known incident.",
      "Sanctions are decided by the Privacy Officer with the practice owner and are documented in the workforce member's file.",
    ]),
  ...policy("P11", "Training",
    "Make sure everyone with access knows how to protect patient information when using the assistant.",
    [
      "Every workforce member completes the Helixona Assistant HIPAA training before their first conversation with the assistant, yearly afterwards, and whenever these policies change materially. Completion is recorded in the training log; no signature is required.",
      "Training records (name, date, trainer, score) are kept for six years in the training log.",
      "Administrators receive additional instruction on the Administration page, the audit review and the incident procedure.",
    ]),
  ...policy("P12", "Policy management",
    "Keep these policies current.",
    [
      "The Privacy Officer reviews these policies yearly and after any incident, system change or change in the law, and records the review in the change history below.",
      "Changes are approved by the practice owner and communicated to all users. Material changes trigger retraining.",
      "Superseded versions are retained for six years.",
    ]),
  h3("Change history"),
  table(["Version", "Date", "Change", "Approved by"], [["1.0", "September 16, 2026", "Initial policies", "[Name]"]], [1200, 2200, 4200, 1760]),
  spacer(),
  h1("Approval"),
  p("Reviewed and approved by the people below. No signature is required: the approval is recorded here, with the name and the date."),
  table(["Role", "Name", "Date"], [["Owner / Medical Director", "[Name]", "[Date]"], ["Privacy Officer", "[Name]", "[Date]"], ["Security Officer", "[Name]", "[Date]"]], [3400, 3600, 2360]),
  pageBreak(),
  h1("Appendix A. Onboarding and offboarding checklist"),
  kv([["Workforce member", ""], ["Role requested (staff / administrator)", ""], ["Requested by", ""], ["Approved by Privacy Officer (date)", ""]]),
  spacer(),
  table(["Onboarding step", "Done by", "Date"], [
    ["Training completed in the assistant (or a paper completion recorded in the training log)", "", ""],
    ["Account created on the Administration page with the approved role", "", ""],
    ["User signed in, changed the temporary password and enrolled the authenticator", "", ""],
    ["Device confirmed: screen lock, updates, encryption", "", ""],
  ], [5600, 2200, 1560]),
  spacer(),
  table(["Offboarding step", "Done by", "Date"], [
    ["Account disabled on the Administration page (sessions revoked)", "", ""],
    ["Removed from any AWS, Anthropic Console or registrar access, if held", "", ""],
    ["Shared projects the user owned reassigned or deleted", "", ""],
    ["Account deleted after 30 days if no longer needed for the audit trail", "", ""],
  ], [5600, 2200, 1560]),
  pageBreak(),
  h1("Appendix B. Quarterly access review"),
  kv([["Quarter", ""], ["Reviewer", ""], ["Date", ""]]),
  spacer(),
  table(["User", "Role", "Still needs access?", "Action taken"], [["", "", "", ""], ["", "", "", ""], ["", "", "", ""], ["", "", "", ""], ["", "", "", ""], ["", "", "", ""]], [3000, 1600, 2000, 2760]),
  spacer(),
  p("Also confirm: number of administrators is the minimum needed; audit log reviewed this quarter; no shared accounts; all users completed yearly training."),
  pageBreak(),
  h1("Appendix C. Security incident report"),
  kv([
    ["Report number", ""], ["Reported by / date and time", ""], ["Discovered how", ""],
    ["Description of the event", ""], ["Systems, accounts and data involved", ""], ["Patients possibly affected (number, not names)", ""],
    ["Containment actions and times", ""], ["Investigation findings (audit log, CloudTrail)", ""],
    ["Breach risk assessment (nature of PHI, who received it, was it acquired or viewed, mitigation)", ""],
    ["Conclusion: breach / not a breach, and why", ""], ["Notifications made (individuals, HHS, media, state) with dates", ""],
    ["Corrective actions and policy changes", ""], ["Closed by / date", ""],
  ], [3200, 6160]),
  pageBreak(),
  h1("Appendix D. Definitions"),
  kv([
    ["PHI / ePHI", "Individually identifiable health information, in any form; ePHI is the electronic form. Includes names, dates, account and policy numbers, and any other identifier combined with health, payment or care information."],
    ["Minimum necessary", "Using or disclosing only the amount of PHI needed for the task."],
    ["Business Associate Agreement (BAA)", "The HIPAA-required contract with a vendor that handles PHI on the clinic's behalf."],
    ["Security incident", "Any attempted or successful unauthorized access, use, disclosure, modification or destruction of information, or interference with the system."],
    ["Breach", "An impermissible use or disclosure of PHI that compromises its security or privacy, unless a documented risk assessment shows a low probability of compromise."],
    ["Administrator", "A user with the administrator role in the Helixona Assistant."],
  ], [2800, 6560]),
];
module.exports = {
  slug: "policies-and-procedures",
  title: "HIPAA Policies and Procedures",
  subtitle: "Helixona Assistant (ai.helixona.com)",
  summary: "The twelve policies that govern how staff and administrators use and operate the assistant, with the procedures behind each one.",
  docx: "Helixona-Assistant-Policies-and-Procedures.docx",
  children,
};
