const { h1, h2, h3, p, b, i, note, bullets, numbered, table, kv, spacer, pageBreak, titleBlock, build } = require("../lib");
const W7 = [400, 2000, 3000, 480, 480, 760, 2240];
const risks = [
  ["R1", "Stolen or phished staff password", "Password of 12+ characters with complexity and history; authenticator app (MFA) required for every user; sign-in rate limiting and Cognito lockout; WAF rate limits on the sign-in endpoints", "Low", "High", "Low", "None beyond current controls. Phishing awareness in training. Owner: Security Officer."],
  ["R2", "Lost or stolen phone or laptop with an open session", "Sessions expire after 15 minutes idle and 12 hours absolute; administrator can disable the user and revoke all sessions immediately; authenticator can be reset by an administrator", "Medium", "Medium", "Low", "Staff must report a lost device the same day (Policy P4). Owner: all workforce."],
  ["R3", "Former staff member keeps access", "Administrator disables the account from the Administration page; server-side sessions are revoked at once; access list reviewed quarterly", "Medium", "High", "Low", "Offboarding the same business day (Policy P3); quarterly access review. Owner: Privacy Officer."],
  ["R4", "Excessive privileges or misuse by an administrator", "Two roles only (staff, administrator); administrator actions are written to the audit log; audit log reviewed weekly; administrators limited to the minimum number needed", "Low", "High", "Low", "Keep no more than two administrators. Owner: Security Officer."],
  ["R5", "PHI sent to the AI vendor without a HIPAA agreement", "Anthropic Business Associate Agreement executed and HIPAA readiness enabled for the clinic's organization on September 15, 2026; the API rejects non-eligible features automatically; only eligible features are used", "Low", "High", "Low", "Review the agreement and eligible-feature list annually. Owner: Security Officer."],
  ["R6", "PHI stored in the cloud account without a HIPAA agreement", "AWS Business Associate Addendum accepted in AWS Artifact on September 22, 2026; only HIPAA-eligible AWS services are used (Appendix A)", "Low", "High", "Low", "Review the addendum and the eligible-services list yearly. Owner: account owner."],
  ["R7", "Interception of data in transit", "TLS 1.2 or higher from the browser to CloudFront; TLS from CloudFront to the load balancer with the clinic's certificate (ai.helixona.com); TLS to the Anthropic API; file uploads over HTTPS presigned URLs; HTTP requests redirected to HTTPS", "Low", "High", "Low", "None. Certificate renews automatically (AWS Certificate Manager)."],
  ["R8", "Unauthorized access to stored conversations or files", "Customer-managed KMS encryption for the database, file storage, logs and secrets; application servers in private subnets with no public IP; least-privilege IAM role for the application; public access blocked on all storage; CloudTrail records every read and write to the PHI tables and the file bucket", "Low", "High", "Low", "None. CloudTrail reviewed monthly (Policy P7)."],
  ["R9", "Data loss, corruption or ransomware", "Point-in-time recovery on all tables; versioned file storage; AWS Backup daily with 35-day retention; infrastructure defined as code and redeployable", "Low", "High", "Low", "[Perform and document one restore test.] Owner: Security Officer. Due: within 30 days of go-live, then yearly."],
  ["R10", "Application vulnerability or injection attack", "AWS WAF managed rule sets and rate limits on CloudFront and on the sign-in service; strict content security policy; input validation on every endpoint; dependencies pinned; infrastructure checked against the AWS HIPAA security rule pack on every deployment", "Medium", "Medium", "Medium", "Apply dependency updates monthly; consider an external penetration test within 12 months. Owner: Security Officer."],
  ["R11", "Inaccurate AI output relied on for care or billing", "The assistant is a drafting and analysis aid; licensed staff remain responsible for clinical and billing decisions; every response is reviewed before use; the system prompt instructs the model to flag uncertainty", "Medium", "Medium", "Medium", "Covered in training (Module 5) and Policy P2. Owner: Privacy Officer."],
  ["R12", "PHI written into logs, metrics or monitoring", "Application logs and audit records never contain message content or file content by design; WAF logging excludes the chat routes; alarms carry counts only", "Low", "Medium", "Low", "None. Re-verify after major releases."],
  ["R13", "Data kept longer than needed", "Conversations and uploaded files are deleted automatically after 30 days; users can delete a conversation at any time; project knowledge files are removed when the project is deleted", "Low", "Low", "Low", "None."],
  ["R14", "Service outage", "Multi-availability-zone deployment; health checks and alarms with email notification; automatic fallback between models when one is unavailable; the clinic's manual processes remain available", "Medium", "Low", "Low", "Downtime procedure in Policy P8."],
  ["R15", "Insider copies PHI out of the system", "Every conversation and file access is attributable to a named user; audit log; minimum-necessary training; sanctions policy", "Medium", "Medium", "Medium", "Accepted with monitoring: weekly audit review, sanctions applied when warranted. Owner: Privacy Officer."],
  ["R16", "Vendor retains data", "Anthropic retains inputs and outputs for 30 days under the BAA safeguards (required for Claude Fable 5.1) and does not train on them; AWS retains nothing beyond the clinic's own storage", "Low", "Low", "Low", "Documented here; no action."],
];
const children = [
  ...titleBlock("HIPAA Security Risk Analysis", "Helixona Assistant (ai.helixona.com)", [
    ["Document", "Security Risk Analysis, 45 CFR 164.308(a)(1)(ii)(A)"],
    ["System", "Helixona Assistant: internal AI assistant for clinic staff"],
    ["Covered entity", "Helixona, Irvine, California"],
    ["Version and date", "1.2, September 22, 2026"],
    ["Prepared by", "[Name], Security Officer"],
    ["Next review", "September 2027, or after any major change to the system"],
  ]),
  pageBreak(),
  h1("1. Purpose and scope"),
  p("The HIPAA Security Rule requires a covered entity to conduct an accurate and thorough assessment of the potential risks and vulnerabilities to the confidentiality, integrity and availability of electronic protected health information (ePHI) it creates, receives, maintains or transmits. This document is that assessment for the Helixona Assistant."),
  p([b("In scope: "), "the Helixona Assistant web application and every component that stores or transmits its data: the clinic's AWS account (148274106093, us-east-1), the Anthropic Claude API under the clinic's Business Associate Agreement, the staff devices used to access it, and the people who administer it."]),
  p([b("Out of scope: "), "the clinic's electronic health record, practice management, email and other systems. Those are covered by the clinic's general risk analysis. This document should be attached to it."]),
  h1("2. System description"),
  p("The Helixona Assistant lets authorized staff use Claude, Anthropic's AI model, for drafting, summaries, translations and analysis of documents such as explanation-of-benefits (EOB) statements and claims. Staff sign in with a password and an authenticator app, type messages, attach PDF or text files, and organize work in projects that share instructions and reference files. Everything is stored inside the clinic's own AWS account."),
  h2("2.1 Components"),
  table(["Component", "Role", "Location"], [
    ["Web application", "Sign-in, chat, file upload, projects, administration pages", "Served by Amazon CloudFront at ai.helixona.com, protected by AWS WAF"],
    ["API service", "Authentication, conversation storage, calls to the AI model, audit logging", "Amazon ECS Fargate containers in private subnets behind an Application Load Balancer"],
    ["Identity", "User accounts, passwords, authenticator enrollment, roles (staff, administrator)", "Amazon Cognito user pool, MFA required"],
    ["Database", "Conversations, messages, projects, sessions, audit events, usage", "Amazon DynamoDB, encrypted with the clinic's KMS key, point-in-time recovery"],
    ["File storage", "Uploaded PDF, TXT, MD and CSV files; project knowledge files", "Amazon S3, encrypted with the clinic's KMS key, versioned, public access blocked"],
    ["Secrets", "API key, session secret, identity client secret", "AWS Secrets Manager, KMS-encrypted"],
    ["AI model", "Generates responses from the conversation and attached documents", "Anthropic Claude API (Sonnet 5, Opus 5.5, Fable 5.1) under the clinic's BAA with HIPAA readiness enabled"],
    ["Monitoring", "Application logs without content, CloudTrail, WAF logs, alarms, backups", "Amazon CloudWatch, AWS CloudTrail, AWS Backup"],
  ], [2000, 3800, 3560]),
  spacer(),
  h2("2.2 Users and roles"),
  ...bullets([
    [b("Staff: "), "use the assistant, their own conversations and files, and any project shared with the clinic."],
    [b("Administrator: "), "everything staff can do, plus creating, disabling and re-enabling users, changing roles, resetting a lost authenticator, and reading the audit and usage reports. Administrators cannot read other users' conversations through the application."],
    [b("AWS account administrator: "), "deploys and operates the infrastructure. This is a clinic workforce member, not an outside vendor."],
  ]),
  h2("2.3 Data handled"),
  table(["Data", "Contains PHI?", "Where it lives", "Retention"], [
    ["Messages typed by staff and the assistant's responses", "Yes, when staff include patient information", "DynamoDB messages table", "30 days, then deleted automatically; users may delete earlier"],
    ["Uploaded files (EOBs, letters, claims)", "Yes", "S3 attachments bucket under the conversation's prefix", "30 days, deleted with the conversation"],
    ["Project instructions and knowledge files", "Possibly", "DynamoDB projects table and S3 under the project's prefix", "Until the project or file is deleted"],
    ["User accounts (name, work email)", "No", "Cognito user pool", "Until the account is deleted"],
    ["Audit log (who did what, when; never content)", "No", "DynamoDB audit table", "Retained for review; no content"],
    ["Application and access logs", "No content by design", "CloudWatch Logs, CloudTrail bucket", "1 year (logs); CloudTrail retained in S3"],
    ["Backups", "Yes (copies of the tables)", "AWS Backup vault, KMS-encrypted", "35 days"],
    ["Data at Anthropic", "Yes, inputs and outputs of each request", "Anthropic, under the BAA", "30 days, then deleted; not used for training"],
  ], [2900, 1500, 2600, 2360]),
  spacer(),
  h1("3. Data flow"),
  ...numbered([
    "A staff member opens ai.helixona.com over TLS and signs in with email, password and a one-time code from an authenticator app. The server creates a session cookie; nothing is stored in the browser beyond that cookie.",
    "Messages travel over TLS to CloudFront, then over TLS to the load balancer and the API containers inside the clinic's private network.",
    "Files are uploaded by the browser directly to the S3 bucket over HTTPS using a short-lived signed URL, then verified by the API before use.",
    "The API assembles the conversation, the attached documents and the project instructions and sends them over TLS to the Anthropic API. The response streams back to the browser the same way.",
    "The API stores the message pair in DynamoDB and writes an audit event without content. Usage is recorded for the daily quota.",
    "After 30 days, or when the user deletes the conversation, the messages and their files are removed automatically.",
  ]),
  h1("4. Method"),
  p("Threats and vulnerabilities were identified from the system design, the AWS and Anthropic HIPAA implementation guidance, and common healthcare incident patterns. Each risk was rated for likelihood and impact on a three-level scale (Low, Medium, High) taking existing safeguards into account, and combined into a residual risk rating. Ratings and actions are reviewed yearly and after any significant change."),
  table(["Rating", "Likelihood", "Impact"], [
    ["Low", "Unlikely within a year given current safeguards", "Limited exposure, quickly contained, few individuals"],
    ["Medium", "Could plausibly happen within a year", "Exposure of several records or short loss of availability"],
    ["High", "Expected to happen without additional safeguards", "Large-scale exposure, notifiable breach, regulatory action"],
  ], [1400, 3980, 3980]),
  spacer(),
  h1("5. Risk register"),
  p("L = likelihood, I = impact. Bracketed actions are open items to complete and date.", { italics: true, size: 18 }),
  table(["#", "Threat or vulnerability", "Existing safeguards", "L", "I", "Residual risk", "Action, owner and due date"], risks, W7),
  spacer(),
  h1("6. Remediation plan"),
  table(["Action", "Owner", "Due", "Status"], [
    ["Confirm the AWS Business Associate Addendum shows Active in AWS Artifact", "Account owner", "Before go-live", "Done, September 22, 2026"],
    ["Perform and document a backup restore test", "Security Officer", "30 days after go-live", "[ ]"],
    ["Enable two-factor authentication for every member of the Claude Console organization; keep the production API key in its own workspace with a spend limit", "Security Officer", "Before go-live", "[ ]"],
    ["Complete workforce training for every user (recorded in the training log inside the assistant)", "Privacy Officer", "Before each user's first conversation", "[ ]"],
    ["Apply dependency and platform updates", "Security Officer", "Monthly", "Recurring"],
    ["Review the user list, roles and audit log", "Privacy Officer", "Quarterly", "Recurring"],
    ["Review this risk analysis, agreements and retention settings", "Security Officer", "Yearly", "Recurring"],
  ], [4800, 1700, 1700, 1160]),
  spacer(),
  h1("7. Conclusion"),
  p("With the safeguards described above in place and the open items in section 6 completed, the residual risk of operating the Helixona Assistant with electronic protected health information is assessed as Low for confidentiality and availability and Medium for integrity of AI-generated content, which is managed through workforce review of every output. The system is appropriate for use with PHI under the clinic's policies."),
  h1("8. Approval"),
  p("Reviewed and approved by the people below. No signature is required: the approval is recorded here, with the name and the date."),
  table(["Role", "Name", "Date"], [["Security Officer", "[Name]", "[Date]"], ["Privacy Officer", "[Name]", "[Date]"], ["Owner / Medical Director", "[Name]", "[Date]"]], [3400, 3600, 2360]),
  pageBreak(),
  h1("Appendix A. HIPAA-eligible AWS services in use"),
  p("Every AWS service that stores or transmits PHI for this system appears on the AWS HIPAA Eligible Services list, as the AWS BAA requires."),
  ...bullets(["Amazon CloudFront and AWS WAF", "Elastic Load Balancing (Application Load Balancer)", "Amazon ECS on AWS Fargate", "Amazon DynamoDB", "Amazon S3", "AWS Key Management Service", "Amazon Cognito", "AWS Secrets Manager", "Amazon CloudWatch and AWS CloudTrail", "AWS Backup", "Amazon VPC"]),
  h1("Appendix B. Agreements register"),
  table(["Vendor", "Agreement", "Status", "Reference"], [
    ["Amazon Web Services", "AWS Business Associate Addendum", "Active since September 22, 2026 (accepted by the account owner)", "AWS Artifact, account 148274106093"],
    ["Anthropic", "Business Associate Agreement with HIPAA readiness", "Active since September 15, 2026 (enabled by the account owner)", "Claude Console, Settings, Privacy"],
  ], [2000, 3000, 2400, 1960]),
  spacer(),
  h1("Appendix C. Change history"),
  table(["Version", "Date", "Change", "Author"], [["1.0", "September 16, 2026", "Initial analysis", "[Name]"], ["1.1", "September 22, 2026", "AWS Business Associate Addendum accepted; remediation item closed", "[Name]"], ["1.2", "September 22, 2026", "Opus model updated to Claude Opus 5.5 (same agreement and safeguards)", "[Name]"]], [1200, 2200, 4200, 1760]),
];
module.exports = {
  slug: "risk-analysis",
  title: "HIPAA Security Risk Analysis",
  subtitle: "Helixona Assistant (ai.helixona.com)",
  summary: "What could go wrong with patient information in the assistant, the safeguards in place, and the open items with owners and due dates.",
  docx: "Helixona-Assistant-Risk-Analysis.docx",
  children,
};
