const { h1, h2, h3, p, b, i, note, bullets, numbered, table, kv, spacer, pageBreak, titleBlock, build } = require("../lib");
/**
 * Knowledge check. The same list feeds the Word file, the answer key and the online check in the
 * app (build.js writes it to packages/core/src/training-quiz.generated.ts, where the API grades it).
 */
const LETTERS = ["A", "B", "C", "D"];
const passingScore = 10;
// `module` ties each question to the module it checks; the in-app course asks them module by module.
const quiz = [
  { module: 1, text: "Who does HIPAA apply to at Helixona?", options: ["Only the doctors.", "The clinic and every member of its workforce, including administrative staff.", "Only the company that runs the software."], answer: "B", why: "HIPAA duties apply to the clinic and to each workforce member." },
  { module: 2, text: "Which of these is PHI?", options: ["A patient's name next to an appointment date.", "The clinic's address.", "A blank claim form."], answer: "A", why: "A name with a date of care identifies the patient and relates to care." },
  { module: 3, text: "Which tool may receive patient information?", options: ["Any AI chatbot with a good privacy policy.", "Only the Helixona Assistant at ai.helixona.com.", "Your personal account on a consumer AI product, if you delete the chat afterwards."], answer: "B", why: "Only the approved tool has HIPAA agreements and the clinic's safeguards." },
  { module: 3, text: "Who is responsible for a clinical or billing decision made using the assistant's output?", options: ["The assistant.", "Anthropic.", "The licensed staff member who reviews and uses it."], answer: "C", why: "Licensed staff own every clinical and billing decision." },
  { module: 4, text: "A coworker is out sick and asks you to sign in with your account so they can finish a letter. What do you do?", options: ["Share the code once.", "Decline; accounts are personal and an administrator can create one for them.", "Sign in for them on your computer."], answer: "B", why: "Accounts are personal; every action must be attributable to one person." },
  { module: 4, text: "Your phone with the authenticator app is stolen on Saturday. When do you report it?", options: ["Monday morning.", "The same day, to the Security Officer.", "Only if you notice unusual activity."], answer: "B", why: "Same-day reporting lets an administrator disable the account or reset the authenticator." },
  { module: 4, text: "You are on a shared front-desk computer and step away for lunch. What do you do first?", options: ["Nothing; the screen locks eventually.", "Sign out of the assistant.", "Close the browser tab only."], answer: "B", why: "Signing out prevents someone else from using your session." },
  { module: 5, text: "You need the assistant to summarize one patient's EOB. The PDF you have covers ten patients. What is the right step?", options: ["Upload the whole file.", "Upload only the pages for that patient, or redact the others.", "Paste all ten into the message."], answer: "B", why: "Minimum necessary: include only the information the task needs." },
  { module: 5, text: "The assistant drafts an appeal letter with a claim number and denial code. Before sending it you must:", options: ["Send it; the assistant is accurate.", "Check the claim number, dates and reasons against the source document.", "Ask the assistant if it is sure."], answer: "B", why: "The assistant can be wrong; the person is responsible for the result." },
  { module: 5, text: "How long are conversations kept?", options: ["Forever.", "30 days after the last activity, or until you delete them.", "Until the end of the year."], answer: "B", why: "Retention is 30 days after the last activity; users may delete sooner." },
  { module: 6, text: "You notice a conversation in a shared project that contains a patient's full record for no work reason. What do you do?", options: ["Ignore it.", "Report it to the Security Officer within an hour.", "Delete it yourself and say nothing."], answer: "B", why: "Suspected incidents are reported within an hour and never handled alone." },
  { module: 7, text: "What can happen if you look at a patient's information without a work reason?", options: ["Nothing, as long as you do not share it.", "Sanctions from retraining up to termination, and possibly legal penalties.", "A reminder email."], answer: "B", why: "Access without a work reason is a violation; sanctions range up to termination and legal penalties may apply." },
];
const optionsLine = (q) => q.options.map((o, k) => `${LETTERS[k]}. ${o}`).join(" ");
const children = [
  ...titleBlock("Workforce Training", "HIPAA and the Helixona Assistant", [
    ["Document", "Training modules, knowledge check and training log"],
    ["Audience", "Every workforce member with an account; administrators complete the additional section"],
    ["Duration", "About 25 minutes"],
    ["Version and date", "1.2, September 23, 2026"],
    ["Owner", "[Name], Privacy Officer"],
    ["Frequency", "Before first sign-in, yearly, and after material policy changes"],
  ]),
  pageBreak(),
  h1("How to use this training"),
  ...numbered([
    "Read modules 1 to 7 (about 20 minutes). Signed-in staff can take the training as a course inside the assistant (Training in the sidebar): each module is followed by its own questions, with feedback, and progress is saved as you go.",
    `Complete the knowledge check. A score of ${passingScore} out of ${quiz.length} or better is required; retake it if needed. Online, the questions are asked module by module in the course, or all at once at ai.helixona.com/documentation/workforce-training; the paper version below is the alternative. The assistant stays locked, for administrators too, until the check is passed (or a paper completion is recorded by an administrator).`,
    "Nothing to sign: passing the check is recorded in the training log with your name, email and the date, and confirms the statements in \"What completing the training means\" below.",
    "The training log in the Administration page records every online completion; the Privacy Officer adds paper completions to it.",
  ]),
  h1("Module 1. Why this matters"),
  p("HIPAA is the federal law that protects patients' health information. It applies to Helixona and to each of us as members of its workforce. Protecting that information is part of the care we give: patients share it with us because they trust us. The same law sets penalties for the clinic and, in serious cases, for individuals, when information is mishandled. California adds its own rules (the Confidentiality of Medical Information Act) that reinforce the same duties."),
  p("This training covers one system, the Helixona Assistant. The clinic's general HIPAA training still applies to everything else you do."),
  h1("Module 2. What counts as protected health information"),
  p("Protected health information (PHI) is any information that identifies a patient and relates to their health, care or payment. It is PHI whether it is on paper, on a screen or in a file. Examples of identifiers:"),
  ...bullets(["Name, address, phone number, email", "Dates: birth, appointment, admission, service, death", "Medical record, account, policy, claim and member numbers", "Photos, signatures, voice", "Anything else that could identify the person when combined with health or payment information"]),
  p([b("Rule of thumb: "), "if a stranger reading it could work out who the patient is, it is PHI. Treat it that way."]),
  h1("Module 3. What the Helixona Assistant is, and is not"),
  p("The Helixona Assistant is the clinic's private way to use Claude, an AI model made by Anthropic. It runs in the clinic's own cloud account, both Amazon Web Services and Anthropic have signed HIPAA agreements with the clinic, and every conversation and file stays under the clinic's control. It is approved for patient information."),
  table(["Approved uses", "Not approved"], [
    ["Drafting letters, messages and appeal letters", "Clinical diagnosis or treatment decisions on its own"],
    ["Summarizing and translating documents", "Sending its output to a patient without a person reading it"],
    ["Analyzing explanation-of-benefits statements, claims and denials", "Personal use of any kind"],
    ["Preparing plain-language explanations for patients", "Entering patient information into any other AI tool or website"],
    ["Organizing recurring work in projects with shared instructions", "Sharing your account or your authenticator"],
  ], [4680, 4680]),
  spacer(),
  note("The assistant is a capable drafting and analysis aid. It can also be confidently wrong. You are responsible for what you use and send."),
  h1("Module 4. Signing in"),
  ...bullets([
    [b("Address: "), "https://ai.helixona.com. Use no other address. If the browser shows a security warning, stop and tell the Security Officer."],
    [b("Password: "), "at least 12 characters with upper and lower case letters, a number and a symbol. Never reuse it anywhere else."],
    [b("Authenticator app: "), "at your first sign-in you scan a QR code with Google Authenticator, Microsoft Authenticator, 1Password or Authy. From then on you enter the 6-digit code from the app after your password."],
    [b("Lost or new phone: "), "tell the Security Officer the same day. An administrator resets your authenticator and you enroll again at the next sign-in."],
    [b("Sessions: "), "you are signed out after 15 minutes without activity. On a shared computer, sign out yourself when you step away."],
    [b("Forgot your password: "), "use the link on the sign-in page. A code is sent to your work email."],
  ]),
  h1("Module 5. Using it safely"),
  h3("Minimum necessary"),
  p("Include only the patient information the task needs. Summarizing one patient's EOB does not need the other nine patients on the same statement. Redact or split the file first."),
  h3("Review every output"),
  p("Check names, dates, amounts, claim numbers and reasons against the source document before you use or send anything. If the assistant says it is unsure, treat that as a flag to verify."),
  h3("Files"),
  p("You can attach PDF, TXT, MD and CSV files. Attach only what the task needs. Files are stored with the conversation and deleted with it."),
  h3("Projects"),
  p("A project gives every conversation in it the same instructions and reference files. A private project is yours; a project shared with the clinic is visible to every staff member. Do not put patient information in a shared project's name, description, instructions or files unless everyone needs it."),
  h3("Delete when done"),
  p("Conversations are deleted automatically after 30 days. Delete them sooner when the work is finished. Keep results only in the clinic's approved systems, never on personal devices or personal email."),
  h3("One approved tool"),
  p("Patient information goes into the Helixona Assistant and nowhere else. Consumer AI chatbots, translation websites and personal accounts are not approved, even if you delete the chat afterwards."),
  h1("Module 6. Recognizing and reporting incidents"),
  p("Report to the Security Officer within one hour if you notice, or even suspect, any of these:"),
  ...bullets([
    "A lost or stolen phone, laptop or authenticator",
    "A sign-in you did not make, or a code request you did not trigger",
    "An email or message asking for your password or code, even if it looks like it comes from the clinic",
    "Patient information sent or shown to the wrong person",
    "Patient information in a place it should not be, such as a shared project",
    "Anything else that feels wrong",
  ]),
  p("Reporting a suspected incident is never penalized. Do not investigate or delete anything yourself; the Security Officer needs the trail intact."),
  h1("Module 7. Consequences"),
  p("Violating the clinic's policies, for example sharing an account, entering patient information into an unapproved tool, or looking at a patient's information without a work reason, results in sanctions from retraining up to termination, and may involve legal penalties. The policies exist to protect patients and to protect you."),
  h1("For administrators only"),
  ...bullets([
    [b("Creating accounts: "), "only after the Privacy Officer's approval. Give the staff role unless the administrator role is approved in writing. The new user completes the training inside the assistant before their first conversation."],
    [b("Disabling accounts: "), "the same business day someone leaves. Disable revokes every session immediately."],
    [b("Reset MFA: "), "only after verifying the person's identity in person or by calling a known number."],
    [b("Weekly audit review: "), "open Administration, Audit; look for sign-ins outside working hours, repeated failures, and administrative changes you did not expect. Report anything unusual."],
    [b("Never "), "ask a user for their password or authenticator code. You never need them."],
  ]),
  h1("Quick reference"),
  table(["Do", "Don't"], [
    ["Sign in only at ai.helixona.com with your password and authenticator", "Share your account, password or code with anyone"],
    ["Use only the patient information the task needs", "Upload documents about patients unrelated to the task"],
    ["Check every output against the source before using it", "Send the assistant's text to a patient unread"],
    ["Delete conversations when the work is done", "Save output with patient information to personal devices or email"],
    ["Report lost devices and anything suspicious within an hour", "Put patient information into any other AI tool or website"],
    ["Sign out on shared computers", "Investigate or delete evidence yourself after an incident"],
  ], [4680, 4680]),
  pageBreak(),
  h1("Knowledge check"),
  p(`Choose one answer per question. Passing score: ${passingScore} of ${quiz.length}.`),
  ...quiz.flatMap((q, n) => [
    p([b(`${n + 1}. `), q.text]),
    p(optionsLine(q), { size: 20 }),
  ]),
  kv([["Name", ""], ["Date", ""], ["Score", `        / ${quiz.length}`]], [2000, 7360]),
  pageBreak(),
  h1("Answer key (for the trainer)"),
  table(["Question", "Answer", "Why"], quiz.map((q, n) => [String(n + 1), q.answer, q.why]), [1200, 1000, 7160]),
  pageBreak(),
  h1("What completing the training means"),
  p("Passing the knowledge check, online or on paper, is recorded in the training log with the workforce member's name, email and the date. No signature is required. By completing it, the workforce member confirms that they:"),
  ...numbered([
    "Completed the training \"HIPAA and the Helixona Assistant\" and passed the knowledge check.",
    "Received and read the Helixona Assistant Policies and Procedures.",
    "Will use only the minimum necessary patient information, review every output before using it, and enter patient information only into the Helixona Assistant.",
    "Will keep their password and authenticator private, sign out on shared computers, and report a lost device or any suspected incident within one hour.",
    "Understand that violations lead to sanctions up to and including termination.",
  ]),
  pageBreak(),
  h1("Training log"),
  p("Kept by the Privacy Officer for six years.", { italics: true, size: 18 }),
  table(["Name", "Role", "Training date", "Trainer", "Score"], Array.from({ length: 12 }, () => ["", "", "", "", ""]), [2800, 1800, 1800, 2000, 960]),
];
module.exports = {
  slug: "workforce-training",
  title: "Workforce Training",
  runningTitle: "Workforce Training: HIPAA and the Helixona Assistant",
  subtitle: "HIPAA and the Helixona Assistant",
  summary: "The training every user completes before their first sign-in: seven short modules, a quick reference and a knowledge check, with nothing to sign.",
  docx: "Helixona-Assistant-Workforce-Training.docx",
  children,
  quiz: {
    version: "1.2",
    passingScore,
    questions: quiz,
    modules: children.filter((n) => n.type === "h" && n.level === 1 && /^Module \d+\./.test(n.text)).map((n) => ({ id: Number(n.text.match(/^Module (\d+)\./)[1]), title: n.text })),
  },
};
