const { h1, h2, h3, p, b, i, note, bullets, numbered, table, kv, signatures, spacer, pageBreak, titleBlock, build } = require("../lib");
const quiz = [
  ["A coworker is out sick and asks you to sign in with your account so they can finish a letter. What do you do?", "A. Share the code once. B. Decline; accounts are personal and an administrator can create one for them. C. Sign in for them on your computer.", "B"],
  ["Which of these is PHI?", "A. A patient's name next to an appointment date. B. The clinic's address. C. A blank claim form.", "A"],
  ["You need the assistant to summarize one patient's EOB. The PDF you have covers ten patients. What is the right step?", "A. Upload the whole file. B. Upload only the pages for that patient, or redact the others. C. Paste all ten into the message.", "B"],
  ["The assistant drafts an appeal letter with a claim number and denial code. Before sending it you must:", "A. Send it; the assistant is accurate. B. Check the claim number, dates and reasons against the source document. C. Ask the assistant if it is sure.", "B"],
  ["Which tool may receive patient information?", "A. Any AI chatbot with a good privacy policy. B. Only the Helixona Assistant at ai.helixona.com. C. Your personal account on a consumer AI product, if you delete the chat afterwards.", "B"],
  ["Your phone with the authenticator app is stolen on Saturday. When do you report it?", "A. Monday morning. B. The same day, to the Security Officer. C. Only if you notice unusual activity.", "B"],
  ["How long are conversations kept?", "A. Forever. B. 30 days after the last activity, or until you delete them. C. Until the end of the year.", "B"],
  ["You notice a conversation in a shared project that contains a patient's full record for no work reason. What do you do?", "A. Ignore it. B. Report it to the Security Officer within an hour. C. Delete it yourself and say nothing.", "B"],
  ["You are on a shared front-desk computer and step away for lunch. What do you do first?", "A. Nothing; the screen locks eventually. B. Sign out of the assistant. C. Close the browser tab only.", "B"],
  ["Who is responsible for a clinical or billing decision made using the assistant's output?", "A. The assistant. B. Anthropic. C. The licensed staff member who reviews and uses it.", "C"],
];
const children = [
  ...titleBlock("Workforce Training", "HIPAA and the Helixona Assistant", [
    ["Document", "Training module, knowledge check, acknowledgment and training log"],
    ["Audience", "Every workforce member with an account; administrators complete the additional section"],
    ["Duration", "About 25 minutes"],
    ["Version and date", "1.0, September 16, 2026"],
    ["Owner", "[Name], Privacy Officer"],
    ["Frequency", "Before first sign-in, yearly, and after material policy changes"],
  ]),
  pageBreak(),
  h1("How to use this training"),
  ...numbered([
    "Read modules 1 to 7 (about 20 minutes).",
    "Complete the knowledge check. A score of 8 out of 10 or better is required; retake it if needed.",
    "Sign the acknowledgment on the last page and return it to the Privacy Officer.",
    "The Privacy Officer records the completion in the training log.",
  ]),
  h1("Module 1. Why this matters"),
  p("HIPAA is the federal law that protects patients' health information. It applies to Helixona and to each of us as members of its workforce. Protecting that information is part of the care we give: patients share it with us because they trust us. The same law sets penalties for the clinic and, in serious cases, for individuals, when information is mishandled. California adds its own rules (the Confidentiality of Medical Information Act) that reinforce the same duties."),
  p("This training covers one system, the Helixona Assistant. The clinic's general HIPAA training still applies to everything else you do."),
  h1("Module 2. What counts as protected health information"),
  p("Protected health information (PHI) is any information that identifies a patient and relates to their health, care or payment. It is PHI whether it is on paper, on a screen or in a file. Examples of identifiers:"),
  ...bullets(["Name, address, phone number, email", "Dates: birth, appointment, admission, service, death", "Medical record, account, policy, claim and member numbers", "Photos, signatures, voice", "Anything else that could identify the person when combined with health or payment information"]),
  p([b("Rule of thumb: "), "if a stranger reading it could work out who the patient is, it is PHI. Treat it that way."]),
  h1("Module 3. What the Helixona Assistant is, and is not"),
  p("The Helixona Assistant is the clinic's private way to use Claude, an AI model made by Anthropic. It runs in the clinic's own cloud account, both Amazon Web Services and Anthropic have signed HIPAA agreements with the clinic, and every conversation and file stays under the clinic's control. It is approved for patient information."),
  table(["Approved uses", "Not approved"], [
    ["Drafting letters, messages and appeal letters", "Clinical diagnosis or treatment decisions on its own"],
    ["Summarizing and translating documents", "Sending its output to a patient without a person reading it"],
    ["Analyzing explanation-of-benefits statements, claims and denials", "Personal use of any kind"],
    ["Preparing plain-language explanations for patients", "Entering patient information into any other AI tool or website"],
    ["Organizing recurring work in projects with shared instructions", "Sharing your account or your authenticator"],
  ], [4680, 4680]),
  spacer(),
  note("The assistant is a capable drafting and analysis aid. It can also be confidently wrong. You are responsible for what you use and send."),
  h1("Module 4. Signing in"),
  ...bullets([
    [b("Address: "), "https://ai.helixona.com. Use no other address. If the browser shows a security warning, stop and tell the Security Officer."],
    [b("Password: "), "at least 12 characters with upper and lower case letters, a number and a symbol. Never reuse it anywhere else."],
    [b("Authenticator app: "), "at your first sign-in you scan a QR code with Google Authenticator, Microsoft Authenticator, 1Password or Authy. From then on you enter the 6-digit code from the app after your password."],
    [b("Lost or new phone: "), "tell the Security Officer the same day. An administrator resets your authenticator and you enroll again at the next sign-in."],
    [b("Sessions: "), "you are signed out after 15 minutes without activity. On a shared computer, sign out yourself when you step away."],
    [b("Forgot your password: "), "use the link on the sign-in page. A code is sent to your work email."],
  ]),
  h1("Module 5. Using it safely"),
  h3("Minimum necessary"),
  p("Include only the patient information the task needs. Summarizing one patient's EOB does not need the other nine patients on the same statement. Redact or split the file first."),
  h3("Review every output"),
  p("Check names, dates, amounts, claim numbers and reasons against the source document before you use or send anything. If the assistant says it is unsure, treat that as a flag to verify."),
  h3("Files"),
  p("You can attach PDF, TXT, MD and CSV files. Attach only what the task needs. Files are stored with the conversation and deleted with it."),
  h3("Projects"),
  p("A project gives every conversation in it the same instructions and reference files. A private project is yours; a project shared with the clinic is visible to every staff member. Do not put patient information in a shared project's name, description, instructions or files unless everyone needs it."),
  h3("Delete when done"),
  p("Conversations are deleted automatically after 30 days. Delete them sooner when the work is finished. Keep results only in the clinic's approved systems, never on personal devices or personal email."),
  h3("One approved tool"),
  p("Patient information goes into the Helixona Assistant and nowhere else. Consumer AI chatbots, translation websites and personal accounts are not approved, even if you delete the chat afterwards."),
  h1("Module 6. Recognizing and reporting incidents"),
  p("Report to the Security Officer within one hour if you notice, or even suspect, any of these:"),
  ...bullets([
    "A lost or stolen phone, laptop or authenticator",
    "A sign-in you did not make, or a code request you did not trigger",
    "An email or message asking for your password or code, even if it looks like it comes from the clinic",
    "Patient information sent or shown to the wrong person",
    "Patient information in a place it should not be, such as a shared project",
    "Anything else that feels wrong",
  ]),
  p("Reporting a suspected incident is never penalized. Do not investigate or delete anything yourself; the Security Officer needs the trail intact."),
  h1("Module 7. Consequences"),
  p("Violating the clinic's policies, for example sharing an account, entering patient information into an unapproved tool, or looking at a patient's information without a work reason, results in sanctions from retraining up to termination, and may involve legal penalties. The policies exist to protect patients and to protect you."),
  h1("For administrators only"),
  ...bullets([
    [b("Creating accounts: "), "only after the Privacy Officer's approval and the user's signed training acknowledgment. Give the staff role unless the administrator role is approved in writing."],
    [b("Disabling accounts: "), "the same business day someone leaves. Disable revokes every session immediately."],
    [b("Reset MFA: "), "only after verifying the person's identity in person or by calling a known number."],
    [b("Weekly audit review: "), "open Administration, Audit; look for sign-ins outside working hours, repeated failures, and administrative changes you did not expect. Report anything unusual."],
    [b("Never "), "ask a user for their password or authenticator code. You never need them."],
  ]),
  h1("Quick reference"),
  table(["Do", "Don't"], [
    ["Sign in only at ai.helixona.com with your password and authenticator", "Share your account, password or code with anyone"],
    ["Use only the patient information the task needs", "Upload documents about patients unrelated to the task"],
    ["Check every output against the source before using it", "Send the assistant's text to a patient unread"],
    ["Delete conversations when the work is done", "Save output with patient information to personal devices or email"],
    ["Report lost devices and anything suspicious within an hour", "Put patient information into any other AI tool or website"],
    ["Sign out on shared computers", "Investigate or delete evidence yourself after an incident"],
  ], [4680, 4680]),
  pageBreak(),
  h1("Knowledge check"),
  p("Circle one answer per question. Passing score: 8 of 10."),
  ...quiz.flatMap((q, n) => [
    p([b(`${n + 1}. `), q[0]]),
    p(q[1], { size: 20 }),
  ]),
  kv([["Name", ""], ["Date", ""], ["Score", "        / 10"]], [2000, 7360]),
  pageBreak(),
  h1("Answer key (for the trainer)"),
  table(["Question", "Answer", "Why"], quiz.map((q, n) => [String(n + 1), q[2], [
    "Accounts are personal; every action must be attributable to one person.",
    "A name with a date of care identifies the patient and relates to care.",
    "Minimum necessary: include only the information the task needs.",
    "The assistant can be wrong; the person is responsible for the result.",
    "Only the approved tool has HIPAA agreements and the clinic's safeguards.",
    "Same-day reporting lets an administrator disable the account or reset the authenticator.",
    "Retention is 30 days after the last activity; users may delete sooner.",
    "Suspected incidents are reported within an hour and never handled alone.",
    "Signing out prevents someone else from using your session.",
    "Licensed staff own every clinical and billing decision.",
  ][n]]), [1200, 1000, 7160]),
  pageBreak(),
  h1("Acknowledgment"),
  p("I confirm that:"),
  ...numbered([
    "I completed the training \"HIPAA and the Helixona Assistant\" and passed the knowledge check.",
    "I received and read the Helixona Assistant Policies and Procedures.",
    "I will use only the minimum necessary patient information, review every output before using it, and enter patient information only into the Helixona Assistant.",
    "I will keep my password and authenticator private, sign out on shared computers, and report a lost device or any suspected incident within one hour.",
    "I understand that violations lead to sanctions up to and including termination.",
  ]),
  spacer(),
  signatures(["Workforce member: [Name and role]", "Trainer / Privacy Officer: [Name]"]),
  pageBreak(),
  h1("Training log"),
  p("Kept by the Privacy Officer for six years.", { italics: true, size: 18 }),
  table(["Name", "Role", "Training date", "Trainer", "Score", "Acknowledgment on file"], Array.from({ length: 12 }, () => ["", "", "", "", "", ""]), [2400, 1500, 1500, 1700, 900, 1360]),
];
module.exports = {
  slug: "workforce-training",
  title: "Workforce Training",
  runningTitle: "Workforce Training: HIPAA and the Helixona Assistant",
  subtitle: "HIPAA and the Helixona Assistant",
  summary: "The training every user completes before their first sign-in: seven short modules, a quick reference, a knowledge check and the acknowledgment form.",
  docx: "Helixona-Assistant-Workforce-Training.docx",
  children,
};
