#!/usr/bin/env node
/**
 * Builds the HIPAA documents for the clinic from the content under `content/`:
 *   - Word files (.docx) into packages/web/public/docs/ (served at /docs/<file> for download)
 *   - JSON trees into packages/web/src/docs/ (rendered by the app's Documentation page)
 * Run `npm install` once in this folder, then `node build.js`.
 */
const fs = require("fs");
const path = require("path");
const { renderDocx } = require("./render-docx");

const docs = ["risk", "policies", "training"].map((name) => require(`./content/${name}`));
const webRoot = path.resolve(__dirname, "../../packages/web");
const docxDir = path.join(webRoot, "public/docs");
const jsonDir = path.join(webRoot, "src/docs");

(async () => {
  fs.mkdirSync(docxDir, { recursive: true });
  fs.mkdirSync(jsonDir, { recursive: true });
  for (const doc of docs) {
    const docxPath = path.join(docxDir, doc.docx);
    fs.writeFileSync(docxPath, await renderDocx(doc));
    const jsonPath = path.join(jsonDir, `${doc.slug}.json`);
    const { quiz, ...tree } = doc;
    fs.writeFileSync(jsonPath, JSON.stringify(tree) + "\n");
    console.log(`${doc.title}: ${path.relative(process.cwd(), docxPath)}, ${path.relative(process.cwd(), jsonPath)}`);
    if (quiz) {
      // The knowledge check: the API grades it (core), and the published demo simulates the API.
      const ts = path.resolve(__dirname, "../../packages/core/src/training-quiz.generated.ts");
      fs.writeFileSync(ts, [
        "// Generated by tools/hipaa-docs/build.js from content/training.js. Do not edit.",
        `export const TRAINING_VERSION = ${JSON.stringify(quiz.version)};`,
        `export const TRAINING_PASSING_SCORE = ${quiz.passingScore};`,
        "export const TRAINING_MODULES: readonly { id: number; title: string }[] = " + JSON.stringify(quiz.modules) + ";",
        "export const TRAINING_QUIZ: readonly { module: number; text: string; options: readonly string[]; answer: string; why: string }[] = " + JSON.stringify(quiz.questions, null, 2) + ";",
        "",
      ].join("\n"));
      const demo = path.join(webRoot, "src/demo/training-quiz.json");
      fs.writeFileSync(demo, JSON.stringify(quiz) + "\n");
      console.log(`  knowledge check: ${path.relative(process.cwd(), ts)}, ${path.relative(process.cwd(), demo)}`);
    }
  }
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
